apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-service.fullname" . }}
  labels:
    {{- include "grpc-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.grpc.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "grpc-service.selectorLabels" . | nindent 4 }}
