apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: golang-gcp-bootstrap

build:
  artifacts:
    - image: gcr.io/freegcpproject-469318/example-backend
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  # Using local builds and pushing to GCR
  local:
    push: true
    useDockerCLI: true
  # Commented out to avoid Cloud Build costs
  # googleCloudBuild:
  #   projectId: your-project-id

deploy:
  helm:
    releases:
      - name: example-backend
        chartPath: helm/grpc-service
        valuesFiles:
          - helm/grpc-service/values.yaml
        setValues:
          image.repository: gcr.io/freegcpproject-469318/example-backend
          image.tag: latest
          replicaCount: 2
          autoscaling.enabled: false
          ingress.enabled: false
        namespace: default
        wait: true

portForward:
  - resourceType: service
    resourceName: example-backend
    port: 9090
    localPort: 9090
  - resourceType: service
    resourceName: example-backend
    port: 8080
    localPort: 8080



profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.dev
      - op: replace
        path: /deploy/helm/releases/0/setValues/replicaCount
        value: 1
      - op: replace
        path: /deploy/helm/releases/0/setValues/autoscaling.enabled
        value: false

  - name: staging
    patches:
      - op: replace
        path: /build/tagPolicy
        value:
          sha256: {}
      - op: replace
        path: /deploy/helm/releases/0/setValues/replicaCount
        value: 1
      - op: replace
        path: /deploy/helm/releases/0/setValues/autoscaling.enabled
        value: false
      - op: replace
        path: /deploy/helm/releases/0/setValues/ingress.enabled
        value: true

  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/tagPolicy
        value:
          sha256: {}
      - op: replace
        path: /deploy/helm/releases/0/setValues/replicaCount
        value: 1
      - op: replace
        path: /deploy/helm/releases/0/setValues/autoscaling.enabled
        value: false
      - op: replace
        path: /deploy/helm/releases/0/setValues/ingress.enabled
        value: true
      - op: replace
        path: /deploy/helm/releases/0/setValues/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /deploy/helm/releases/0/setValues/resources/limits/memory
        value: 1Gi
