apiVersion: v2
name: grpc-service
description: A modern Go gRPC service for GKE
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - grpc
  - go
  - kubernetes
  - gke
home: https://github.com/hefeicoder/golang_gcp_bootstrap
sources:
  - https://github.com/hefeicoder/golang_gcp_bootstrap
maintainers:
  - name: hefeicoder
    email: your-email@example.com
