# Default values for test-backend (Cost-optimized)
replicaCount: 1  # Reduced from 3 to 1 for cost savings

image:
  repository: test-backend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9090
  annotations: {}

ingress:
  enabled: false  # Disabled to avoid load balancer costs
  className: ""
  annotations: {}
  hosts:
    - host: grpc.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m    # Reduced from 1000m to 500m
    memory: 512Mi # Reduced from 1Gi to 512Mi
  requests:
    cpu: 100m    # Reduced from 500m to 100m
    memory: 128Mi # Reduced from 512Mi to 128Mi

autoscaling:
  enabled: false  # Disabled to avoid scaling costs
  minReplicas: 1  # Reduced from 2 to 1
  maxReplicas: 3  # Reduced from 10 to 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# gRPC specific configuration
grpc:
  port: 9090
  healthPort: 8080
  reflection: true

# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

# Logging configuration
logging:
  level: info
  format: json

# Environment variables
env:
  - name: GRPC_PORT
    value: "9090"
  - name: HEALTH_PORT
    value: "8080"
  - name: LOG_LEVEL
    value: "info"
