# Default values for test-backend (Cost-optimized)
replicaCount: 1  # Reduced from 3 to 1 for cost savings

image:
  repository: gcr.io/freegcpproject-469318/example-backend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 9090
  nodePort: 30090
  annotations: {}

ingress:
  enabled: false  # Disabled to avoid load balancer costs
  className: ""
  annotations: {}
  hosts:
    - host: your-domain.com  # Replace with your actual domain
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 50m     # Minimal for e2-micro
    memory: 64Mi  # Minimal for e2-micro
  requests:
    cpu: 10m     # Minimal for e2-micro
    memory: 16Mi  # Minimal for e2-micro

autoscaling:
  enabled: false  # Disabled to avoid scaling costs
  minReplicas: 1  # Reduced from 2 to 1
  maxReplicas: 3  # Reduced from 10 to 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# gRPC specific configuration
grpc:
  port: 9090
  healthPort: 8080
  reflection: true

# Monitoring configuration
monitoring:
  enabled: false  # Disabled for e2-micro to save resources
  serviceMonitor:
    enabled: false
    interval: 30s

# Logging configuration
logging:
  level: info
  format: json

# Environment variables
env:
  - name: GRPC_PORT
    value: "9090"
  - name: HEALTH_PORT
    value: "8080"
  - name: LOG_LEVEL
    value: "info"
